name: CI

on: [push, pull_request]

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint (ESLint + Prettier)
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
